### PR TITLE
fix #3

### LINKED ISSUE #3: Bisect stops when failing to kill server which is already dead
I am honored to give you your first issue.

🐛 When the tool fails to quit the server process, everything just stops!

image

### PR DESCRIPTION
**Pull request by joaomoreno**
Fixes #3

### CODE REVIEW

File: src/launcher.ts [hunk 1]
```diff
@@ -68,7 +68,16 @@ class Launcher {
 
         return {
             stop: () => new Promise<void>((resolve, reject) => {
-                kill(cp.pid!, error => error ? reject(error) : resolve())
+                kill(cp.pid!, error => {
+                    if (error && /There is no running instance of the task/i.test(error.message)) {
```
Comment (bpasero) [inline src/launcher.ts]: This seems like a windows only solution right? I was checking how we deal with `tree-kill` errors in VSCode and found this snippet:

```ts
try {
	return await promisify(kill)(electronPid);
} catch (error) {
	try {
		process.kill(electronPid, 0); // throws an exception if the process doesn't exist anymore
		logger.log(`Error tearing down electron client (pid: ${electronPid}, attempt: ${retries}): ${error}`);
	} catch (error) {
		return; // Expected when process is gone
	}
}
```

Maybe we can do the similar here?

**Review by bpasero — CHANGES_REQUESTED** [review]

File: src/launcher.ts [hunk 2]
```diff
@@ -68,7 +68,16 @@ class Launcher {
...
+                        console.warn(error);
+                        resolve();
+                    } else if (error) {
+                        reject(error);
+                    } else {
+                        resolve();
+                    }
+                });
```
Comment (joaomoreno) [inline src/launcher.ts]:
```suggestion
                const pid = cp.pid!;
                kill(pid, error => {
                    if (error) {
                        try {
                            process.kill(pid, 0);
                        } catch (error) {
                            resolve();      // process doesn't exist anymore... so, all good
                            return;
                        }
    
                        reject(error);
                    } else {
                        resolve();
                    }
                });
```
